Accessing/Changing specific elements, rows, columns, etc


In [6]:
# import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [9]:
# Get a specific element [r,c]
print(a[1,5])


13


In [11]:
# Get a specifi row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specific col
a[:, 0]

array([1, 8])

In [15]:
# [startindex: endindex: stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [18]:
a[1,5]= 20

print(a)

a[:,2] =[1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [17]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


*3-d example


In [21]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
print(b[0,0,0])


1


In [25]:
print("hello")

hello
