# Initializing Different Types of Arays

In [12]:
# all 0s matrix
import numpy as np
a= np.zeros((2,3,3))

In [8]:
np.ones((1,2))

array([[1., 1.]])

In [10]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [14]:
# any other number (full_like)
np.full_like(a, 4)

array([[[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]]])

In [17]:
# random decimal numbers
np.random.rand(4,2,3)

array([[[0.23751192, 0.42167853, 0.13858179],
        [0.29427762, 0.74983727, 0.33989558]],

       [[0.48918111, 0.58743527, 0.93606137],
        [0.49868405, 0.50290257, 0.09668484]],

       [[0.47447526, 0.38523653, 0.2526041 ],
        [0.83451814, 0.98262092, 0.07022715]],

       [[0.33500859, 0.96911791, 0.60938969],
        [0.02765242, 0.27797593, 0.88531857]]])

In [30]:
# random integer values
np.random.randint(7, size=(3,3))

array([[3, 4, 3],
       [4, 5, 1],
       [0, 2, 0]], dtype=int32)

In [32]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [46]:
a=np.ones((5,5))
# print(a)

z= np.zeros((3,3))
z[1,1]=9

a[1:4,1:4]=z
print(a)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
x= np.array([1,2,3])
y= x.copy()
y[1]=100
print(x)
print(y)

[1 2 3]
[  1 100   3]
