# Mathematics

In [11]:
import numpy as np
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [16]:
a+2
print(a)

[3 4 5 6 7]


In [17]:
b = np.array([1,0,1,0,1])
a+b

array([4, 4, 6, 6, 8])

In [18]:
a**2

array([ 9, 16, 25, 36, 49])

In [19]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ])

## Linear Algebra

In [24]:
a = np.ones((2,3))
b= np.full((3,2),2)
np.matmul(a,b)



array([[6., 6.],
       [6., 6.]])

In [27]:
# finding determinant
c = np.identity(3)
print(np.linalg.det(c))

1.0


## Statistics

In [29]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.min(stats, axis=0)

array([1, 2, 3])

In [34]:
np.sum

<function sum at 0x00000195FFD5D870>

In [36]:
np.sum(stats)

np.int64(21)

## Reorganizing arrays

In [40]:
before = np.array([[1,2,3,4],[4,5,6,7]])
print(before)

after= before.reshape((4,2))
print(after)

[[1 2 3 4]
 [4 5 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [43]:
# vertically stacking vecotr
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])