# Miscellaneous

### Load data from a file


In [15]:
import numpy as np
filedata = np.genfromtxt('data.txt', delimiter=',', dtype=int)
filedata


array([[    1,    13,    21,    24,    35,    26,    89,   483, 38459,
         3854,  3958,   394],
       [    1,    13,    21,    24,    35,    26,    89,   483, 38459,
         3854,  3958,   394],
       [    1,    13,    21,    24,    35,    26,    89,   483, 38459,
         3854,  3958,   394],
       [    1,    13,    21,    24,    35,    26,    89,   483, 38459,
         3854,  3958,   394],
       [    1,    13,    21,    24,    35,    26,    89,   483, 38459,
         3854,  3958,   394]])

### Boolean masking and advanced indexing

In [8]:
filedata[filedata>50]

array([   89,   483, 38459,  3854,  3958,   394,    89,   483, 38459,
        3854,  3958,   394,    89,   483, 38459,  3854,  3958,   394,
          89,   483, 38459,  3854,  3958,   394,    89,   483, 38459,
        3854,  3958,   394])

In [10]:
# we can index with a list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [16]:
np.all(filedata>50, axis=1)


array([False, False, False, False, False])

In [17]:
print("hello")

hello
