In [4]:
import numpy as np


In [16]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [9]:
b= np.array([[9,8,7],[1,2,3]])
print(b)

[[9 8 7]
 [1 2 3]]


In [ ]:
#Get dimension
a.ndim

1

In [13]:
# Get Shape
b.shape

(2, 3)

In [18]:
# Get Type
a.dtype

dtype('int16')

In [20]:
# Get size
a.itemsize


2

In [22]:
#Get total size
a.size

3